version: 0.2

# AWS CodeBuild specification for Maven-pnpm monorepo
# Uses Dockerfile.ci for consistent builds across GitHub Actions and AWS CodeBuild
#
# Build Modes:
#   1. DOCKER_BUILD=true  - Build inside Docker container (recommended)
#   2. DOCKER_BUILD=false - Build directly on CodeBuild host (legacy)

env:
  variables:
    # Build mode: use Docker container or native CodeBuild
    DOCKER_BUILD: "true"

    # Build configuration
    MAX_PARALLEL_BUILDS: "4"
    SKIP_TESTS: "false"

  parameter-store:
    # GitHub PAT for downstream PRs (store in AWS Systems Manager Parameter Store)
    GITHUB_TOKEN: /codebuild/maven-pnpm-monorepo/github-token

  secrets-manager:
    # Alternative: Store GitHub token in AWS Secrets Manager
    # GITHUB_TOKEN: arn:aws:secretsmanager:region:account-id:secret:github-token

phases:
  install:
    commands:
      - echo "Build started at $(date)"
      - echo "Build mode: DOCKER_BUILD=$DOCKER_BUILD"

      # Configure git for changeset operations
      - git config --global user.name "AWS CodeBuild"
      - git config --global user.email "codebuild@amazon.com"

      # Install GitHub CLI for downstream PRs (needed in post_build)
      - |
        if [ ! -x "$(command -v gh)" ]; then
          echo "Installing GitHub CLI..."
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          apt update
          apt install gh jq -y
        fi

      # Authenticate with GitHub CLI
      - echo "$GITHUB_TOKEN" | gh auth login --with-token

  pre_build:
    commands:
      - echo "Detecting changed modules..."

      # For Docker builds, we need pnpm installed on host for change detection
      - |
        if [ "$DOCKER_BUILD" = "true" ]; then
          echo "Installing pnpm for change detection..."
          corepack enable
          corepack prepare pnpm@9 --activate
          pnpm install --frozen-lockfile
        fi

      # Detect changed modules using maven.js CLI
      - |
        CHANGED_MODULES=$(node scripts/src/maven.js changed --csv 2>/dev/null || echo "")
        echo "Changed modules: $CHANGED_MODULES"

      # Check if there are changes to build
      - |
        if [ -z "$CHANGED_MODULES" ]; then
          echo "No modules changed - skipping build"
          echo "SKIP_BUILD=true" >> build.env
        else
          echo "SKIP_BUILD=false" >> build.env
          echo "CHANGED_MODULES=${CHANGED_MODULES}" >> build.env
        fi

  build:
    commands:
      - echo "Building changed modules..."

      # Load environment
      - source build.env

      # Skip if no changes
      - |
        if [ "$SKIP_BUILD" = "true" ]; then
          echo "No modules to build - skipping"
          exit 0
        fi

      # Docker-based build using Dockerfile.ci
      - |
        if [ "$DOCKER_BUILD" = "true" ]; then
          echo "=== Docker Build Mode ==="
          echo "Building modules: $CHANGED_MODULES"

          # Build using Dockerfile.ci with BuildKit
          DOCKER_BUILDKIT=1 docker build \
            -f Dockerfile.ci \
            --target build \
            --build-arg MODULES="$CHANGED_MODULES" \
            --build-arg SKIP_TESTS="$SKIP_TESTS" \
            --build-arg MAVEN_GOAL=install \
            -t monorepo-build:$CODEBUILD_BUILD_NUMBER \
            .

          # Extract build artifacts from container
          echo "Extracting artifacts..."
          CONTAINER_ID=$(docker create monorepo-build:$CODEBUILD_BUILD_NUMBER)
          docker cp $CONTAINER_ID:/workspace/demo-module-a/target ./demo-module-a/ 2>/dev/null || true
          docker cp $CONTAINER_ID:/workspace/demo-module-b/target ./demo-module-b/ 2>/dev/null || true
          docker cp $CONTAINER_ID:/workspace/demo-module-c/target ./demo-module-c/ 2>/dev/null || true
          docker rm $CONTAINER_ID

          # Run tests if not skipped
          if [ "$SKIP_TESTS" = "false" ]; then
            echo "Running tests..."
            DOCKER_BUILDKIT=1 docker build \
              -f Dockerfile.ci \
              --target test \
              --build-arg MODULES="$CHANGED_MODULES" \
              -t monorepo-test:$CODEBUILD_BUILD_NUMBER \
              .

            # Extract test reports
            TEST_CONTAINER_ID=$(docker create monorepo-test:$CODEBUILD_BUILD_NUMBER)
            docker cp $TEST_CONTAINER_ID:/workspace/demo-module-a/target/surefire-reports ./demo-module-a/target/ 2>/dev/null || true
            docker cp $TEST_CONTAINER_ID:/workspace/demo-module-b/target/surefire-reports ./demo-module-b/target/ 2>/dev/null || true
            docker cp $TEST_CONTAINER_ID:/workspace/demo-module-c/target/surefire-reports ./demo-module-c/target/ 2>/dev/null || true
            docker rm $TEST_CONTAINER_ID
          fi

        else
          echo "=== Native Build Mode ==="
          # Legacy: Build directly on CodeBuild host
          node scripts/src/maven.js build \
            --modules "$CHANGED_MODULES" \
            --max-parallel "$MAX_PARALLEL_BUILDS" \
            --goal install \
            $([ "$SKIP_TESTS" = "true" ] && echo "--skip-tests" || echo "--with-tests")
        fi

  post_build:
    commands:
      - echo "Post-build phase - versioning and publishing..."

      # Load environment
      - source build.env

      # Skip if no changes
      - |
        if [ "$SKIP_BUILD" = "true" ]; then
          echo "No modules to publish - skipping"
          exit 0
        fi

      # Apply changeset versions
      - echo "Applying changeset versions..."
      - pnpm changeset version || echo "No changesets to apply"

      # Sync versions between package.json and pom.xml
      - echo "Syncing Maven and package.json versions..."
      - node scripts/src/maven.js sync

      # Commit version changes if any
      - |
        if [ -n "$(git status --porcelain)" ]; then
          echo "Committing version changes..."
          git add .
          git commit -m "chore: version packages [skip ci]

          🤖 Generated by AWS CodeBuild" || true
          git push origin ${CODEBUILD_SOURCE_VERSION##*/} || echo "Push failed - may need manual intervention"
        fi

      # Publish changed modules to GitHub Packages
      - echo "Publishing changed modules to GitHub Packages..."
      - |
        IFS=',' read -ra MODULES <<< "$CHANGED_MODULES"
        for MODULE in "${MODULES[@]}"; do
          echo "Publishing $MODULE to GitHub Packages..."
          ./mvnw -pl "$MODULE" -am clean deploy -DskipTests
        done

      # Create downstream PRs
      - echo "Creating downstream PRs..."
      - |
        IFS=',' read -ra MODULES <<< "$CHANGED_MODULES"
        for MODULE in "${MODULES[@]}"; do
          VERSION=$(cat "$MODULE/package.json" | jq -r '.version')
          echo "Creating downstream PRs for $MODULE version $VERSION"
          node scripts/src/maven.js downstream \
            --module "$MODULE" \
            --version "${VERSION}-SNAPSHOT" || echo "Downstream PR creation failed for $MODULE"
        done

      - echo "Build completed at $(date)"

artifacts:
  files:
    # Preserve build artifacts
    - '*/target/*.jar'
    - '*/target/*.pom'
    - '**/CHANGELOG.md'
    - '*/target/surefire-reports/**/*'

  name: build-artifacts-$(date +%Y%m%d-%H%M%S)

cache:
  paths:
    # Cache Docker layers (when using Docker build mode)
    - '/var/lib/docker/**/*'

    # Cache for native build mode
    - '.m2/repository/**/*'
    - 'node_modules/**/*'
    - '.pnpm-store/**/*'

reports:
  # JUnit test reports
  maven-test-reports:
    files:
      - '*/target/surefire-reports/*.xml'
    file-format: 'JUNITXML'

  # Code coverage reports (if using JaCoCo)
  coverage-reports:
    files:
      - '*/target/site/jacoco/jacoco.xml'
    file-format: 'JACOCOXML'
