version: 0.2

# =============================================================================
# AWS CodeBuild - Maven Monorepo CI (Docker-based)
# =============================================================================
# Uses Dockerfile.ci with maven.js CLI (matches .github/workflows/ci.yml):
#   init    - Generate package.json from pom.xml
#   status  - Check version alignment
#   sync    - Sync versions between package.json and pom.xml
#   changed - Detect changed modules
#   deps    - Show dependency tree
#   build   - Build with dependency-aware parallel execution
# =============================================================================

env:
  variables:
    # Build configuration
    MAX_PARALLEL: "2"
    SKIP_TESTS: "false"

  parameter-store:
    # GitHub PAT for downstream PRs (store in AWS Systems Manager Parameter Store)
    GITHUB_TOKEN: /codebuild/maven-pnpm-monorepo/github-token

  secrets-manager:
    # Alternative: Store GitHub token in AWS Secrets Manager
    # GITHUB_TOKEN: arn:aws:secretsmanager:region:account-id:secret:github-token

phases:
  install:
    commands:
      - echo "Build started at $(date)"

      # Configure git for changeset operations
      - git config --global user.name "AWS CodeBuild"
      - git config --global user.email "codebuild@amazon.com"

      # Install pnpm for change detection on host
      - corepack enable
      - corepack prepare pnpm@9 --activate
      - pnpm install --frozen-lockfile

      # Install GitHub CLI for downstream PRs (needed in post_build)
      - |
        if [ ! -x "$(command -v gh)" ]; then
          echo "Installing GitHub CLI..."
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          apt update
          apt install gh jq -y
        fi

      # Authenticate with GitHub CLI
      - echo "$GITHUB_TOKEN" | gh auth login --with-token

  pre_build:
    commands:
      # -----------------------------------------------------------------------
      # Detect changed modules (on host for git operations)
      # -----------------------------------------------------------------------
      - echo "=== maven.js changed - Detect changed modules ==="
      - |
        CHANGED_MODULES=$(node scripts/src/maven.js changed --csv 2>/dev/null || echo "")
        if [ -z "$CHANGED_MODULES" ]; then
          echo "No modules changed - skipping build"
          echo "SKIP_BUILD=true" >> build.env
          echo "CHANGED_MODULES=" >> build.env
        else
          echo "Changed modules: $CHANGED_MODULES"
          echo "SKIP_BUILD=false" >> build.env
          echo "CHANGED_MODULES=${CHANGED_MODULES}" >> build.env
        fi

      - source build.env

      - echo "=== maven.js deps - Show dependency tree ==="
      - |
        if [ "$SKIP_BUILD" = "false" ]; then
          node scripts/src/maven.js deps
        fi

  build:
    commands:
      # Load environment
      - source build.env

      # Skip if no changes
      - |
        if [ "$SKIP_BUILD" = "true" ]; then
          echo "No modules to build - skipping"
          exit 0
        fi

      # -----------------------------------------------------------------------
      # Docker Build: init -> status -> sync -> build (with tests)
      # Uses Dockerfile.ci with maven.js CLI
      # -----------------------------------------------------------------------
      - echo "=== Docker Build - Build & Test changed modules ==="
      - |
        DOCKER_BUILDKIT=1 docker build \
          -f Dockerfile.ci \
          --target build \
          --build-arg MODULES="$CHANGED_MODULES" \
          --build-arg SKIP_TESTS="$SKIP_TESTS" \
          --build-arg MAVEN_GOAL=install \
          --build-arg MAX_PARALLEL="$MAX_PARALLEL" \
          -t monorepo-build:$CODEBUILD_BUILD_NUMBER \
          .

      # Extract build artifacts from container
      - echo "=== Extracting artifacts from container ==="
      - |
        CONTAINER_ID=$(docker create monorepo-build:$CODEBUILD_BUILD_NUMBER)

        # Extract JARs and test results from each module
        for MODULE in demo-module-a demo-module-b demo-module-c; do
          mkdir -p $MODULE/target
          docker cp $CONTAINER_ID:/workspace/$MODULE/target/. $MODULE/target/ 2>/dev/null || true
        done

        docker rm $CONTAINER_ID

        # Show extracted artifacts
        echo "=== Extracted JARs ==="
        find . -path "*/target/*.jar" -type f | head -20

        echo "=== Extracted test results ==="
        find . -path "*/target/surefire-reports/*.xml" -type f | head -20

  post_build:
    commands:
      - echo "Post-build phase - versioning and publishing..."

      # Load environment
      - source build.env

      # Skip if no changes
      - |
        if [ "$SKIP_BUILD" = "true" ]; then
          echo "No modules to publish - skipping"
          exit 0
        fi

      # -----------------------------------------------------------------------
      # Version: Apply changesets and sync versions (on host for git)
      # -----------------------------------------------------------------------
      - echo "=== maven.js init - Ensure package.json files exist ==="
      - node scripts/src/maven.js init

      - echo "=== Applying changeset versions ==="
      - |
        if [ -d ".changeset" ] && [ "$(ls -A .changeset/*.md 2>/dev/null | wc -l)" -gt 0 ]; then
          echo "Applying changesets..."
          pnpm changeset version

          # Sync Maven versions to match package.json
          echo "=== maven.js sync - Sync versions ==="
          node scripts/src/maven.js sync

          VERSION_UPDATED=true
        else
          echo "No changesets found"
          VERSION_UPDATED=false
        fi

      # Commit version changes if any
      - |
        if [ "$VERSION_UPDATED" = "true" ] && [ -n "$(git status --porcelain)" ]; then
          echo "Committing version changes..."
          git add .
          git commit -m "chore: version packages [skip ci]

          🤖 Generated by AWS CodeBuild" || true
          git push origin ${CODEBUILD_SOURCE_VERSION##*/} || echo "Push failed - may need manual intervention"
        fi

      # -----------------------------------------------------------------------
      # Publish: Deploy to GitHub Packages (Docker-based)
      # -----------------------------------------------------------------------
      - echo "=== Creating Maven settings for GitHub Packages ==="
      - |
        mkdir -p .m2
        cat > .m2/settings.xml << EOF
        <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                                      http://maven.apache.org/xsd/settings-1.0.0.xsd">
          <servers>
            <server>
              <id>github</id>
              <username>codebuild</username>
              <password>${GITHUB_TOKEN}</password>
            </server>
          </servers>
        </settings>
        EOF

      - echo "=== Docker Build - Deploy to GitHub Packages ==="
      - |
        DOCKER_BUILDKIT=1 docker build \
          -f Dockerfile.ci \
          --target build \
          --build-arg MODULES="$CHANGED_MODULES" \
          --build-arg SKIP_TESTS=true \
          --build-arg MAVEN_GOAL=deploy \
          --build-arg MAX_PARALLEL="$MAX_PARALLEL" \
          --secret id=m2settings,src=.m2/settings.xml \
          -t monorepo-deploy:$CODEBUILD_BUILD_NUMBER \
          .

      # -----------------------------------------------------------------------
      # Downstream PRs
      # -----------------------------------------------------------------------
      - echo "=== maven.js downstream - Create downstream PRs ==="
      - |
        IFS=',' read -ra MODULES <<< "$CHANGED_MODULES"
        for MODULE in "${MODULES[@]}"; do
          VERSION=$(cat "$MODULE/package.json" | jq -r '.version')
          echo "Creating downstream PRs for $MODULE version $VERSION"
          node scripts/src/maven.js downstream \
            --module "$MODULE" \
            --target-version "${VERSION}-SNAPSHOT" || echo "Downstream PR creation failed for $MODULE"
        done

      - echo "Build completed at $(date)"

artifacts:
  files:
    # Preserve build artifacts
    - '*/target/*.jar'
    - '*/target/*.pom'
    - '**/CHANGELOG.md'
    - '*/target/surefire-reports/**/*'

  name: build-artifacts-$(date +%Y%m%d-%H%M%S)

cache:
  paths:
    # Docker layer cache
    - '/var/lib/docker/**/*'
    # Node.js dependencies (for change detection on host)
    - 'node_modules/**/*'
    - '.pnpm-store/**/*'

reports:
  # JUnit test reports
  maven-test-reports:
    files:
      - '*/target/surefire-reports/*.xml'
    file-format: 'JUNITXML'

  # Code coverage reports (if using JaCoCo)
  coverage-reports:
    files:
      - '*/target/site/jacoco/jacoco.xml'
    file-format: 'JACOCOXML'
