version: 0.2

# AWS CodeBuild specification for Maven-pnpm monorepo
# Replicates GitHub Actions workflow functionality with selective building,
# versioning, publishing, and downstream PR creation

env:
  variables:
    # Node.js and pnpm configuration
    NODE_VERSION: "20"
    PNPM_VERSION: "9"

    # Maven configuration
    MAVEN_OPTS: "-Dmaven.repo.local=$CODEBUILD_SRC_DIR/.m2/repository"

    # Build configuration
    MAX_PARALLEL_BUILDS: "4"

  parameter-store:
    # GitHub PAT for downstream PRs (store in AWS Systems Manager Parameter Store)
    GITHUB_TOKEN: /codebuild/maven-pnpm-monorepo/github-token

  secrets-manager:
    # Alternative: Store GitHub token in AWS Secrets Manager
    # GITHUB_TOKEN: arn:aws:secretsmanager:region:account-id:secret:github-token

phases:
  install:
    runtime-versions:
      java: corretto21
      nodejs: 20

    commands:
      - echo "Installing dependencies..."

      # Enable corepack for pnpm
      - corepack enable
      - corepack prepare pnpm@${PNPM_VERSION} --activate

      # Install Node.js dependencies
      - pnpm install --frozen-lockfile

      # Install GitHub CLI for downstream PRs
      - |
        if [ ! -x "$(command -v gh)" ]; then
          echo "Installing GitHub CLI..."
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          apt update
          apt install gh -y
        fi

      # Authenticate with GitHub CLI
      - echo "$GITHUB_TOKEN" | gh auth login --with-token

  pre_build:
    commands:
      - echo "Detecting changed modules..."
      - echo "Build started at $(date)"

      # Configure git for changeset operations
      - git config --global user.name "AWS CodeBuild"
      - git config --global user.email "codebuild@amazon.com"

      # Detect changed modules
      - node scripts/src/changed-modules.js --output .artifacts
      - CHANGED_MODULES=$(cat .artifacts/maven-pl.txt || echo "")

      # Log detection results
      - echo "Changed modules detected:"
      - cat .artifacts/summary.txt || echo "No summary available"

      # Check if there are changes to build
      - |
        if [ -z "$CHANGED_MODULES" ]; then
          echo "No modules changed - skipping build"
          exit 0
        fi

      # Export for later phases
      - echo "CHANGED_MODULES=${CHANGED_MODULES}" >> build.env
      - export CHANGED_MODULES

  build:
    commands:
      - echo "Building and testing changed modules..."

      # Load environment
      - source build.env || true

      # Skip if no changes
      - |
        if [ -z "$CHANGED_MODULES" ]; then
          echo "No modules to build"
          exit 0
        fi

      # Build changed modules in parallel
      - echo "Building modules: $CHANGED_MODULES"
      - |
        node scripts/src/parallel-build.js \
          --modules "$CHANGED_MODULES" \
          --max-parallel "$MAX_PARALLEL_BUILDS" \
          --goal install

      # Run tests in parallel
      - echo "Running tests..."
      - |
        node scripts/src/parallel-build.js \
          --modules "$CHANGED_MODULES" \
          --max-parallel "$MAX_PARALLEL_BUILDS" \
          --goal test

  post_build:
    commands:
      - echo "Post-build phase - versioning and publishing..."

      # Load environment
      - source build.env || true

      # Skip if no changes
      - |
        if [ -z "$CHANGED_MODULES" ]; then
          echo "No modules to publish"
          exit 0
        fi

      # Apply changeset versions
      - echo "Applying changeset versions..."
      - pnpm changeset version || echo "No changesets to apply"

      # Sync versions between package.json and pom.xml
      - echo "Syncing Maven and package.json versions..."
      - pnpm maven:sync

      # Commit version changes if any
      - |
        if [ -n "$(git status --porcelain)" ]; then
          echo "Committing version changes..."
          git add .
          git commit -m "chore: version packages [skip ci]

          🤖 Generated by AWS CodeBuild" || true
          git push origin ${CODEBUILD_SOURCE_VERSION##*/} || echo "Push failed - may need manual intervention"
        fi

      # Publish changed modules to GitHub Packages
      - echo "Publishing changed modules to GitHub Packages..."
      - |
        IFS=',' read -ra MODULES <<< "$CHANGED_MODULES"
        for MODULE in "${MODULES[@]}"; do
          echo "Publishing $MODULE to GitHub Packages..."
          mvn -pl "$MODULE" -am clean deploy -DskipTests
        done

      # Create downstream PRs
      - echo "Creating downstream PRs..."
      - |
        IFS=',' read -ra MODULES <<< "$CHANGED_MODULES"
        for MODULE in "${MODULES[@]}"; do
          VERSION=$(cat "$MODULE/package.json" | jq -r '.version')
          echo "Creating downstream PRs for $MODULE version $VERSION"
          pnpm -F @libs/scripts downstream:prs \
            --module "$MODULE" \
            --version "${VERSION}-SNAPSHOT" || echo "Downstream PR creation failed for $MODULE"
        done

      - echo "Build completed at $(date)"

artifacts:
  files:
    # Preserve build artifacts for debugging
    - .artifacts/**/*
    - '*/target/*.jar'
    - '*/target/*.pom'
    - '**/CHANGELOG.md'

  name: build-artifacts-$(date +%Y%m%d-%H%M%S)

cache:
  paths:
    # Cache Maven dependencies
    - '.m2/repository/**/*'

    # Cache Node.js dependencies
    - 'node_modules/**/*'
    - '*/node_modules/**/*'
    - '.pnpm-store/**/*'

reports:
  # JUnit test reports
  maven-test-reports:
    files:
      - '*/target/surefire-reports/*.xml'
    file-format: 'JUNITXML'

  # Code coverage reports (if using JaCoCo)
  coverage-reports:
    files:
      - '*/target/site/jacoco/jacoco.xml'
    file-format: 'JACOCOXML'
